from django.urls import path, include, re_path
from quest    import views
from .views import LoginTracciamento, PasswordResetComplete, PasswordReset, PasswordResetDone, \
                    PasswordResetConfirm, PasswordChangeDone, PasswordChange, Logout


urlpatterns = [
                path('2',views.prova_view,name ='login_utenti' ),
                path('reg/<str:trace>',views.registration_view,name ='registrazione_utenti'),
                path('per',views.registration_anag_view,name ='registrazioni_anagrafica'),
                path('per/<str:a>',views.registration_anag_view,name ='registrazioni_anagrafica'),
                path('stud',views.registration_stud_view,name ='registrazioni_studi'),
                path('stud/<str:a>',views.registration_stud_view,name ='registrazioni_studi'),
#                path('esperienza/', views.candidato_exp_view, name='esperienza_add'),
#                path('ajax/load-lavori/', views.load_lavori, name='ajax_load_lavori'),
                path('lang',views.registration_lang_view,name ='registrazioni_lingue'),
                path('lang/<str:a>',views.registration_lang_view,name ='registrazioni_lingue'),
                path('quest',views.quest_view,name ='registrazioni_questionari'),
                path('per-pg',views.riassunto_candidato,name ='pagina_utente'),
                path('del-l/<str:id>',views.cancella_lingua,name ='cancella_dato'),
                path('del-e/<str:id>',views.cancella_esperienza,name ='cancella_dato'),
                path('del-s/<str:id>',views.cancella_studio,name ='cancella_dato'),
                path('ins/<str:passo_corrente>/',views.gestione_inserimento_view,name ='gestione_inserimento'),
                path('ins/<str:passo_corrente>/<str:trace>/',views.gestione_inserimento_view,name ='gestione_inserimento'),
#                path('accounts/',include('django.contrib.auth.urls')),
                path('login/',LoginTracciamento.as_view(),name ='login'),
                path('login/<str:trace>',LoginTracciamento.as_view(),name ='login'),
                path('logout/',Logout.as_view(),name ='logout'),
                path('psw-r-f/',PasswordReset.as_view(),name ='password_reset'),
                path('psw-r-d/',PasswordResetDone.as_view(),name ='password_reset_done'),
                path('accounts/reset/<uidb64>/<token>/',PasswordResetConfirm.as_view(),name ='password_reset_confirm'),
                path('psw-r-c/',PasswordResetComplete.as_view(),name ='password_reset_complete'),
                path('psw-c-f/',PasswordChange.as_view(),name ='password_change_form'),
                path('psw-c-d/',PasswordChangeDone.as_view(),name ='password_change_done'),
                path('cruscotto',views.dashboard, name='cruscotto'),
                path('can-rec/<int:id>',views.riassunto_candidato_recruiter, name='candidato_recruiter'),
                path('in-out',views.homepage),
                path('inter',views.inter),
                path('utente2', views.utente2),
                path('proxy', views.proxy2),
                path('quest-1', views.quest_1),
                path('quest-2', views.quest_2, name='quest_2'),
                path('proxy', views.proxy2),
                path('rec',views.tabella),
                path('prova-campo',views.prova_campo),
#                path('30',views.RicercaCandidato),
                path('exp/', views.esperienza_create_view, name='esperienza_add'),
                path('exp/<str:a>', views.esperienza_create_view, name='esperienza_add'),
                path('ajax/load-professioni/', views.load_professioni, name='ajax_load_professioni'),
                path('res/', views.residenza_create_view, name='residenza_add'),
                path('res/<str:a>', views.residenza_create_view, name='residenza_add'),
                path('ajax/load-amm2/', views.load_amm2, name='ajax_load_amm2'),
                path('ajax/load-amm3/', views.load_amm3, name='ajax_load_amm3'),
                path('ajax/load-amm4/', views.load_amm4, name='ajax_load_amm4'),
                path('mail/', views.mail),
                path('del-u/', views.oblio),
                path('cns/', views.consenso_form, name='consenso'),
                path('pry/', views.privacy , name='privacy'),
                path('pry/<str:trace>', views.privacy , name='privacy'),
                ]
