# Generated by Django 3.1 on 2021-11-28 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ruolo', models.PositiveSmallIntegerField(choices=[(1, 'recruiter'), (2, 'studente')])),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('stato', models.PositiveSmallIntegerField(choices=[(1, 'RegistrazioneAnagraficaStep'), (2, 'EsperienzeStudiStep')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amm1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amm2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('amm1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.amm1')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Amm3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('amm2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.amm2')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Amm4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('amm3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.amm3')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AziendaLingua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azienda', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'azienda',
                'verbose_name_plural': 'aziende',
                'db_table': 'azienda',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidati',
                'db_table': 'candidato',
            },
        ),
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=6, unique=True)),
                ('testo', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'domanda',
                'verbose_name_plural': 'domande',
                'db_table': 'domanda',
            },
        ),
        migrations.CreateModel(
            name='GestioneInserimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passo_corrente', models.CharField(max_length=256)),
                ('passo_destra', models.CharField(max_length=256)),
                ('passo_sinistra', models.CharField(max_length=256)),
                ('slide', models.IntegerField()),
            ],
            options={
                'verbose_name': 'gestione_inserimenti',
                'verbose_name_plural': 'gestioni_inserimenti',
                'db_table': 'gestione_inserimenti',
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'lingua',
                'verbose_name_plural': 'lingue',
                'db_table': 'lingua',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lingua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quest.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'questionario',
                'verbose_name_plural': 'questionari',
                'db_table': 'questionario',
            },
        ),
        migrations.CreateModel(
            name='QuestionarioDomanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.PositiveSmallIntegerField()),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.domanda')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.questionario')),
            ],
            options={
                'verbose_name': 'questionario_domanda',
                'verbose_name_plural': 'questionari_domanda',
                'db_table': 'questionario_domanda',
                'unique_together': {('questionario', 'domanda'), ('questionario', 'posizione')},
            },
        ),
        migrations.CreateModel(
            name='Titolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lingua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quest.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Testo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=250)),
                ('slide', models.CharField(max_length=25)),
                ('posizione', models.CharField(max_length=25)),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.lingua')),
            ],
            options={
                'verbose_name': 'testo',
                'verbose_name_plural': 'testi',
                'db_table': 'testo',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quest.materia')),
                ('titolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quest.titolo')),
            ],
            options={
                'verbose_name': 'studio',
                'verbose_name_plural': 'studio',
                'db_table': 'studio',
            },
        ),
        migrations.CreateModel(
            name='Settore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lingua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quest.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Professione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lingua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quest.lingua')),
                ('settore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quest.settore')),
            ],
        ),
        migrations.CreateModel(
            name='Previsione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsione', models.DecimalField(decimal_places=2, max_digits=5)),
                ('esito', models.BooleanField()),
                ('algoritmo', models.CharField(max_length=5)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'previsione_corrente',
                'verbose_name_plural': 'previsioni_corrente',
                'db_table': 'previsione_corrente',
            },
        ),
        migrations.CreateModel(
            name='Livello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Linguaconosciuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lingua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.lang')),
                ('livello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.livello')),
            ],
            options={
                'verbose_name': 'lingua_conosciuta',
                'verbose_name_plural': 'lingue_conosciuta',
                'db_table': 'lingua_conosciuta',
            },
        ),
        migrations.AddField(
            model_name='lang',
            name='lingua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quest.lingua'),
        ),
        migrations.CreateModel(
            name='CandidatoResidenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amm1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm1')),
                ('amm2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm2')),
                ('amm3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm3')),
                ('amm4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.amm4')),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.aziendalingua')),
            ],
            options={
                'verbose_name': 'candidato_parametro',
                'verbose_name_plural': 'candidato_parametri',
                'db_table': 'candidato_parametro',
            },
        ),
        migrations.CreateModel(
            name='CandidatoEsperienza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('professione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.professione')),
                ('settore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.settore')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoAzienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.aziendalingua')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidato_azienda',
                'verbose_name_plural': 'candidato_aziende',
                'db_table': 'candidato_azienda',
            },
        ),
        migrations.AddField(
            model_name='aziendalingua',
            name='lingua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.lingua'),
        ),
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'anagrafica',
                'verbose_name_plural': 'anagrafiche',
                'db_table': 'anagrafica',
            },
        ),
        migrations.CreateModel(
            name='AlgoritmoRecruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoritmo', models.CharField(max_length=5)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.aziendalingua')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'algoritmo_recruit',
                'verbose_name_plural': 'algoritmi_recruit',
                'db_table': 'algoritmo_recruit',
            },
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutazione', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1)),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.questionariodomanda')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'risposta',
                'verbose_name_plural': 'risposte',
                'db_table': 'risposta',
                'unique_together': {('utente', 'domanda')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aziendalingua',
            unique_together={('azienda', 'lingua')},
        ),
    ]
