# Generated by Django 3.1 on 2022-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagrafica',
            options={'ordering': ('pk',), 'verbose_name': 'anagrafica', 'verbose_name_plural': 'anagrafiche'},
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='anno',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='giorno',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='mese',
            field=models.IntegerField(default=1),
        ),
    ]
