# Generated by Django 3.1 on 2022-01-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20220119_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagrafica',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='anagrafica',
            name='giorno',
        ),
        migrations.RemoveField(
            model_name='anagrafica',
            name='mese',
        ),
    ]
