# Generated by Django 3.1 on 2022-01-27 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20220127_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatoparametro',
            old_name='giorno',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='candidatoparametro',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
