# Generated by Django 3.1 on 2022-01-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_auto_20220127_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatoparametro',
            old_name='created_at',
            new_name='giorno',
        ),
        migrations.RemoveField(
            model_name='candidatoparametro',
            name='updated_at',
        ),
    ]
