# Generated by Django 3.1 on 2022-02-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0010_auto_20220204_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amm1',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='amm2',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='amm3',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='amm4',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='domanda',
            name='testo',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='testo',
            name='testo',
            field=models.CharField(max_length=500),
        ),
    ]
