# Generated by Django 3.1 on 2022-07-11 15:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0012_auto_20220211_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisioneControllo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoritmo', models.CharField(max_length=5)),
                ('giorno', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.aziendalingua')),
            ],
            options={
                'verbose_name': 'previsione_controllo',
                'verbose_name_plural': 'previsioni_controllo',
                'db_table': 'previsione_controllo',
            },
        ),
        migrations.CreateModel(
            name='CandidatoConsenso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consenso', models.CharField(max_length=5)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidato_consenso',
                'verbose_name_plural': 'candidati_consenso',
                'db_table': 'candidato_consenso',
            },
        ),
        migrations.CreateModel(
            name='AziendaConsenso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consenso', models.CharField(max_length=5)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.aziendalingua')),
            ],
            options={
                'verbose_name': 'azienda_consenso',
                'verbose_name_plural': 'aziende_consenso',
                'db_table': 'azienda_consenso',
            },
        ),
    ]
