# Generated by Django 3.1 on 2022-07-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0013_aziendaconsenso_candidatoconsenso_previsionecontrollo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aziendaconsenso',
            old_name='candidato',
            new_name='azienda',
        ),
    ]
