# Generated by Django 3.1 on 2022-07-19 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0014_auto_20220712_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagination', models.IntegerField()),
                ('artisticinterests', models.IntegerField()),
                ('emotionality', models.IntegerField()),
                ('adventurousness', models.IntegerField()),
                ('intellect', models.IntegerField()),
                ('liberalism', models.IntegerField()),
                ('rabbia', models.IntegerField()),
                ('aggressività', models.IntegerField()),
                ('depression', models.IntegerField()),
                ('selfconsciousness', models.IntegerField()),
                ('vulnerability', models.IntegerField()),
                ('ansia', models.IntegerField()),
                ('dipendenza', models.IntegerField()),
                ('autoefficacia', models.IntegerField()),
                ('orientamentorisultato', models.IntegerField()),
                ('autodisciplina', models.IntegerField()),
                ('personalitaproattiva', models.IntegerField()),
                ('ordine', models.IntegerField()),
                ('sensodovere', models.IntegerField()),
                ('cauteladelibera', models.IntegerField()),
                ('fiduciaaltri', models.IntegerField()),
                ('altruismo', models.IntegerField()),
                ('empatia', models.IntegerField()),
                ('simpatia', models.IntegerField()),
                ('cooperazione', models.IntegerField()),
                ('modestia', models.IntegerField()),
                ('onesta', models.IntegerField()),
                ('gregarieta', models.IntegerField()),
                ('ricercasensazioni', models.IntegerField()),
                ('assertivita', models.IntegerField()),
                ('livelloattivita', models.IntegerField()),
                ('emozionipositive', models.IntegerField()),
                ('capacitagestireemozionipositive', models.IntegerField()),
                ('intelligenzaemotiva', models.IntegerField()),
                ('desiderabilitasociale', models.IntegerField()),
                ('percezionecontrollogeneraleesterno', models.IntegerField()),
                ('percezionecontrollogeneraleinterno', models.IntegerField()),
                ('openess', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
                ('coscienziosita', models.IntegerField()),
                ('piacevolezza', models.IntegerField()),
                ('estroversione', models.IntegerField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scala',
                'verbose_name_plural': 'scale',
                'db_table': 'scala',
            },
        ),
    ]
