# Generated by Django 3.1 on 2022-07-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0015_scala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scala',
            old_name='aggressività',
            new_name='aggressivita',
        ),
        migrations.RenameField(
            model_name='scala',
            old_name='coscienziosita',
            new_name='impulsivita',
        ),
        migrations.RenameField(
            model_name='scala',
            old_name='estroversione',
            new_name='orientamentoapprend',
        ),
        migrations.RemoveField(
            model_name='scala',
            name='neuroticism',
        ),
        migrations.RemoveField(
            model_name='scala',
            name='openess',
        ),
        migrations.RemoveField(
            model_name='scala',
            name='piacevolezza',
        ),
    ]
