# Generated by Django 3.1 on 2022-11-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0016_auto_20220720_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsione',
            name='esito',
            field=models.CharField(max_length=2),
        ),
    ]
