# Generated by Django 3.1 on 2022-12-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0017_auto_20221130_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('slide', models.CharField(max_length=25)),
                ('posizione', models.CharField(max_length=25)),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.lingua')),
            ],
            options={
                'verbose_name': 'privacy',
                'verbose_name_plural': 'privacys',
                'db_table': 'privay',
            },
        ),
    ]
