# Generated by Django 3.1 on 2022-12-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0018_privacy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='privacy',
            table='privacy',
        ),
    ]
